---
# Path to TopJobs advertisement images
image_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/small_batch"

# Path to the full Topjobs dataset
data_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/data_full.xlsx"

# Path to the dataset of ONET occupation titles
occ_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/onet_occ_titles.txt"

# Path to the dataset of ONET alternate occupation titles
alt_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/onet_alt_titles.txt"

# Path to the dataset of technologies associated with ONET occupations
tech_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/onet_tech_skills.txt"

# Path to the dataset of manually annotated tags for the Topjobs data sample
tags_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/cs_sample_tags.csv"

# Path to the OCR outputs for the Topjobs data sample
ocr_output_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/small_batch.csv"

# Date range during which lockdown was implemented (ASSUMPTION: All dates beyond 2020-03-01 are considered to be under lockdown)
lockdown_date_range: [
  "2020-03-01",
  "2022-12-31"
]

# Path to ONET Corpus
onet_corpus_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/outputs/onet_corpus.csv"

# Path to matches file
matches_path: "C:/Users/DELL/Documents/LIRNEasia/ADB/data/outputs/sample_matches.csv"

# Embedding Model for Top2Vec topic modelling
embedding_model: "universal-sentence-encoder"

# Text Column used for Top2Vec topic modelling
text_column_name: "clean_text"